# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx2048M

# Fabric Properties
# check these on https://fabricmc.net/develup
minecraft_version=1.21.8
yarn_mappings=1.21.8+build.1
loader_version=0.17.2
loom_version=1.11-SNAPSHOT

# Fabric API
fabric_version=0.133.0+1.21.8

# Mod Properties
mod_name = Essential Commands
mod_id = essential_commands
mod_version = 0.38.4
# TODO @1.0.0: migrate to dev.jpcode
maven_group = com.fibermc
archives_base_name = essential_commands

# Dependencies
permissions_api_version=0.4.1
placeholder_api_version=2.7.2+1.21.8
pal_version=1.14.0
vanish_version=1.6.0+1.21.8
mixinextras_version=0.5.0
# snakeyaml does not use semver - see https://repo.maven.apache.org/maven2/org/yaml/snakeyaml/
snakeyaml_version=2.5

jetbrains_annotations_version = 22.0.0ge
junit_bom_version=5.10.1

# Publish
# Modrinth
modrinth_project_id=6VdDUivB
mr_game_versions = 1.21.8
mr_relations_required = fabric-api
mr_relations_optional = luckperms,player-roles,vanish
mr_relations_embedded = pal,placeholder-api,fabric-permissions-api
mr_relations_incompatible =

# CurseForge
cf_project_id=475964
cf_game_versions = Fabric,Java 21,1.21.8
cf_relations_required = fabric-api
cf_relations_optional = luckperms,player-roles,meliusvanish
cf_relations_embedded = pal,text-placeholder-api
cf_relations_tools =
cf_relations_incompatible = ftb-teams-fabric
#modmenu
# GitHub
github_repo=John-Paul-R/essential-commands
gh_owner=John-Paul-R
gh_repo=essential-commands

mod_menu_version=3.0.0
