# Gradle Configuration
org.gradle.jvmargs=-Xmx2048M

# Fabric Properties
# check these on https://fabricmc.net/develup
minecraft_version=1.21.11
yarn_mappings=1.21.11+build.1
loader_version=0.18.2
loom_version=1.13-SNAPSHOT

# Fabric API
fabric_version=0.139.4+1.21.11

# Mod Properties
mod_name = Essential Commands
mod_id = essential_commands
mod_version = 0.38.6
# TODO @1.0.0: migrate to dev.jpcode
maven_group = com.fibermc
archives_base_name = essential_commands

# Common Publishing
game_versions=1.21.11
gh_owner=John-Paul-R
gh_repo=essential-commands

# Dependencies
permissions_api_version=0.6.1
placeholder_api_version=2.8.1+1.21.10
pal_version=1.15.0
vanish_version=1.6.1+1.21.9-rc1
mixinextras_version=0.5.0
snakeyaml_version=2.5
jetbrains_annotations_version=22.0.0
junit_bom_version=5.10.1
mod_menu_version=3.0.0

# Platform-Specific Publishing
# Modrinth
modrinth_project_id=6VdDUivB
mr_relations_required=fabric-api
mr_relations_optional=luckperms,player-roles,vanish
mr_relations_embedded=pal,placeholder-api,fabric-permissions-api
mr_relations_incompatible=

# CurseForge
cf_project_id=475964
cf_relations_required=fabric-api
cf_relations_optional=luckperms,player-roles,meliusvanish
cf_relations_embedded=pal,text-placeholder-api
cf_relations_incompatible=ftb-teams-fabric
