plugins {
    id 'maven-publish'
}

// Declare dependencies
dependencies {
    testImplementation platform("org.junit:junit-bom:${project.junit_bom_version}")
    testImplementation 'org.junit.jupiter:junit-jupiter'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}

publishing {
    // Declare all publications
    publications {
        mavenJava(MavenPublication) {
            artifactId project.mod_id
            groupId project.maven_group
            version project.version
            // Main
            artifact(remapJar) { builtBy remapJar }
            // Sources
            artifact(sourcesJar) {
                builtBy remapSourcesJar

            }
        }
    }
}
