plugins {
    id 'maven-publish'
}

dependencies {
    // Required dependencies (expose as api so root project can use them)
    modApi "net.fabricmc.fabric-api:fabric-api:${project.fabric_version}"
    modApi "eu.pb4:placeholder-api:${project.placeholder_api_version}"

    testImplementation platform("org.junit:junit-bom:${project.junit_bom_version}")
    testImplementation 'org.junit.jupiter:junit-jupiter'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
    testImplementation "net.fabricmc:fabric-loader-junit:${project.loader_version}"
}

publishing {
    // Declare all publications
    publications {
        mavenJava(MavenPublication) {
            artifactId project.mod_id
            groupId project.maven_group
            version project.version
            // Main
            artifact(remapJar) { builtBy remapJar }
            // Sources
            artifact(sourcesJar) {
                builtBy remapSourcesJar

            }
        }
    }
}
